allow_remote_control password
remote_control_password "" set-background-opacity
dynamic_background_opacity yes

font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14

background_opacity 0.7

scrollback_lines 20000

tab_title_template "{index}:{title}"

# Reload config
map ctrl+shift+r combine : load_config_file : send_text all echo Reloaded config

## Keybindings
# kitty_mod ctrl+shift

# The \x18 is the hexadecimal ASCII code for ctrl+x.
# To send a literal ctrl+x.
map ctrl+shift+x send_text all \x18

map alt+w copy_to_clipboard
map ctrl+y paste_from_clipboard

map ctrl+shift+enter launch --type=tab --cwd=current
map ctrl+enter launch --cwd=current
#map ctrl+x>k close_window
map ctrl+o next_window
#map ctrl+x>o next_window
map alt+Tab next_tab
# set tab title
map alt+r set_tab_title
map alt+shift+r set_tab_title
#
map ctrl+x>k close_tab
map super+k close_tab

# layouts
# ctrl+shift+l next_layout
map ctrl+x>` goto_layout stack
map ctrl+x>1 goto_layout grid
map ctrl+x>3 goto_layout tall
map ctrl+x>2 goto_layout fat
#map ctrl>2 goto_layout splits
#map ctrl+x> goto_layout 

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

# scrolling
map alt+v scroll_page_up
map ctrl+v scroll_page_down
map alt+shift+, scroll_home
map alt+shift+. scroll_end
map ctrl+shift+a scroll_to_prompt -1
map ctrl+, scroll_to_prompt -1

# tabs
map alt+shift+left move_tab_backward
map alt+shift+right move_tab_forward

## Navigation mode
# Create a new "nav" mode (mw)
map --new-mode nav ctrl+c>ctrl+t
# Exit the manage window mode
map --mode nav esc pop_keyboard_mode
map --mode nav ctrl+g pop_keyboard_mode

